/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import modelo.Calculadora;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class CaculadoraTest {
    
    private Calculadora cal;
    
    public CaculadoraTest(){
        cal = new Calculadora();
    }

    @Test
    public void somarTest(){
        assertEquals(6,cal.soma(3,3));
    }
    
    @Test
    public void subtrairTest(){
        assertEquals(1,cal.subtrai(5,4));
    }

    @Test
    public void dividirTest(){
        assertEquals(5,cal.divide(10,2));
    }

    @Test
    public void multiplicarTest(){
        assertEquals(4,cal.multiplica(2,2));
    }        
}