/*
 * This Java source file was generated by the Gradle 'init' task.
 */

 import modelo.Calculadora;

public class App {

    public static void main(String [] Args){

        Calculadora cal = new Calculadora();

        cal.soma(2,2);
        
    }

}






    // public static void main(String[] args) {
    //     System.out.println(new App().getGreeting());
    // }
}
