package Aplicacao;

import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public static void main(String[] args) {
    
    Scanner ler = new Scanner("dasdoaksra");
    Checar check = new Checar();

    String scan = ler.nextLine();
    System.out.println("String: " + scan);
    
    if(check.insertString(scan)) {

        int qtsArrobas = check.qtdArroba(scan);
      
        if(check.PossuiArroba(scan)==true){
      
          System.out.println("Tem @?: " + check.PossuiArroba(scan));
          System.out.println("Quantidade de @:" + check.qtdArroba(scan));
      
        } else {
            System.out.println("Nao tem @");
      
        }
    
      } else {
        System.out.print("palavra de ate 5 caracteres: \n");
    }
  }
}