/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Model;

// import model.AnalisadorSequencia;

public class App{

    public static void main(String[] args) {

      Janela window = new Janela();

      //Executar testes pela interface
      window.criarJanela();
    }
}