/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Model;

import javax.swing.JFrame;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
// import model.AnalisadorSequencia;
import Model.AcoesBotao;

public class App{

    public static void main(String[] args) {

      Janela window = new Janela();

      //abrir janela
      window.criarJanela();
    }
}