/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import Aplicacao.App;
import Aplicacao.Checar;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class ChecarTest{
    
    private Checar check;
    
    public ChecarTest(){
        check = new Checar(); 
    }
    
    //verifica se esta vazio 
    @Test
    public void insertStringTest(){
        String teste = ""; 
        assertEquals(false, check.insertString(teste));
    }

    //verifica se string e menor que 5
    @Test
    public void menorque5(){
        String teste = "aaaaaaaa"; 
        assertEquals(true, check.insertString(teste));
    }

    // verifica se tem arroba
    @Test
    public void temArrobaTest(){
        String teste = "wsaaa"; 
        assertEquals(false, check.PossuiArroba(teste));
    }    

    // verifica posicao do primeiro @
    @Test
    public void quantidadeArroba(){
        String teste = "@saa"; 
        assertEquals(0, check.qtdArroba(teste));
    }  

    //Verifica posicao do primeiro @ com dois @@
    @Test
    public void quantidadeArroba2(){
        String teste = "sa@w@"; 
        assertEquals(2, check.qtdArroba(teste));
    }  
}