/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// public class App {
//     public String getGreeting() {
//         return "Hello world.";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
// }

public class Somador{
 
    public int somar(int x, int y){
    return (x+y);
    }
}