/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// import org.junit.Test;
// import static org.junit.Assert.*;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;


// Código da classe de teste
public class SomadorTest{
    private Somador somador;
    public SomadorTest(){
    somador = new Somador();
    }
    @Test
    public void somarTest(){
    assertEquals(2,somador.somar(1,1));
    }
}

// public class AppTest {
//     @Test public void testAppHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }

